// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      _ensureConfigured(
        web,
        platform: 'web',
        requiredVariables: _FirebaseEnv.webRequiredVariables,
      );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        _ensureConfigured(
          android,
          platform: 'android',
          requiredVariables: _FirebaseEnv.androidRequiredVariables,
        );
        return android;
      case TargetPlatform.iOS:
        _ensureConfigured(
          ios,
          platform: 'ios',
          requiredVariables: _FirebaseEnv.iosRequiredVariables,
        );
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _FirebaseEnv.webApiKey,
    appId: _FirebaseEnv.webAppId,
    messagingSenderId: _FirebaseEnv.messagingSenderId,
    projectId: _FirebaseEnv.projectId,
    authDomain: _FirebaseEnv.authDomain,
    storageBucket: _FirebaseEnv.storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _FirebaseEnv.androidApiKey,
    appId: _FirebaseEnv.androidAppId,
    messagingSenderId: _FirebaseEnv.messagingSenderId,
    projectId: _FirebaseEnv.projectId,
    storageBucket: _FirebaseEnv.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _FirebaseEnv.iosApiKey,
    appId: _FirebaseEnv.iosAppId,
    messagingSenderId: _FirebaseEnv.messagingSenderId,
    projectId: _FirebaseEnv.projectId,
    storageBucket: _FirebaseEnv.storageBucket,
    iosBundleId: _FirebaseEnv.iosBundleId,
  );

  static void _ensureConfigured(
    FirebaseOptions options, {
    required String platform,
    required List<String> requiredVariables,
  }) {
    final missing = <String>[
      if (options.apiKey.isEmpty) requiredVariables[0],
      if (options.appId.isEmpty) requiredVariables[1],
      if (options.messagingSenderId.isEmpty) requiredVariables[2],
      if (options.projectId.isEmpty) requiredVariables[3],
      if (options.storageBucket?.isEmpty ?? true) requiredVariables[4],
      if (platform == 'web' && (options.authDomain?.isEmpty ?? true))
        requiredVariables[5],
      if (platform == 'ios' && (options.iosBundleId?.isEmpty ?? true))
        requiredVariables[5],
    ];

    if (missing.isNotEmpty) {
      throw UnsupportedError(
        'Firebase is not configured for $platform. Copy '
        '`firebase.env.example.json` to `firebase.env.json`, fill in your '
        'values, and run Flutter with '
        '`--dart-define-from-file=firebase.env.json`. Missing: '
        '${missing.join(', ')}',
      );
    }
  }
}

class _FirebaseEnv {
  static const String authDomain = String.fromEnvironment('FIREBASE_AUTH_DOMAIN');
  static const String projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const String storageBucket = String.fromEnvironment(
    'FIREBASE_STORAGE_BUCKET',
  );
  static const String messagingSenderId = String.fromEnvironment(
    'FIREBASE_MESSAGING_SENDER_ID',
  );

  static const String webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');

  static const String androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String androidAppId = String.fromEnvironment(
    'FIREBASE_ANDROID_APP_ID',
  );

  static const String iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static const String iosAppId = String.fromEnvironment('FIREBASE_IOS_APP_ID');
  static const String iosBundleId = String.fromEnvironment(
    'FIREBASE_IOS_BUNDLE_ID',
  );

  static const List<String> webRequiredVariables = <String>[
    'FIREBASE_WEB_API_KEY',
    'FIREBASE_WEB_APP_ID',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_AUTH_DOMAIN',
  ];

  static const List<String> androidRequiredVariables = <String>[
    'FIREBASE_ANDROID_API_KEY',
    'FIREBASE_ANDROID_APP_ID',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
  ];

  static const List<String> iosRequiredVariables = <String>[
    'FIREBASE_IOS_API_KEY',
    'FIREBASE_IOS_APP_ID',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_IOS_BUNDLE_ID',
  ];
}
