// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGu9ahGFfdIBV0pth3XUl5rY88xb4c5LU',
    appId: '1:1060207776877:web:cf0b7f4456bffebfb2db64',
    messagingSenderId: '1060207776877',
    projectId: 'myfluttercookbook',
    authDomain: 'myfluttercookbook.firebaseapp.com',
    storageBucket: 'myfluttercookbook.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFPv-QV0DUKHzF5JnRs1wNIFESHQquMg',
    appId: '1:1060207776877:android:6c998e2054fc57acb2db64',
    messagingSenderId: '1060207776877',
    projectId: 'myfluttercookbook',
    storageBucket: 'myfluttercookbook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMZxckkVBUv8URlJ7GzWN8qHcaGAXnek',
    appId: '1:1060207776877:ios:f93a661448135487b2db64',
    messagingSenderId: '1060207776877',
    projectId: 'myfluttercookbook',
    storageBucket: 'myfluttercookbook.firebasestorage.app',
    iosBundleId: 'com.ethan.flutterApp',
  );
}
